### PR TITLE
[draft] Incremental updates

### PR DESCRIPTION
**Pull request by eridal**
Reopening #19 but this time on this same repo.

Also I've fixed the code to make standard happy

### CODE REVIEW

**Comment by zeke** [comment]
I've uninstalled the CI reporter app so we won't see those comments any more.

This looks good to me, though I didn't read the new build code exhaustively. Should I ship it?

**Comment by eridal** [comment]
@zeke let's wait for merging this. There are quite a few things that I'd like to validate before doing so we can make sure nothing slips and consumers are not impacted.

**Comment by eridal** [comment]
Hmmm something is not right, seems like npm and github have diverged

Last night [v1.354.0](https://www.npmjs.com/package/all-the-package-repos/v/1.354.0) was released by the script, but in github there is no commit nor tag.

Here's the supposedly "successful" execution: https://github.com/nice-registry/all-the-package-repos/runs/513166209

**Comment by eridal** [comment]
Cool, github actions are finally working!!

The last update failed but that was due to the out of sync between npm and github: the version v1.354.0 will be different depending on where you look :'(

Ok, so next step is to give the new updater a test run - stay tune!

**Comment by eridal** [comment]
@zeke  This is almost done. At this point there are two files, so we can compare results:

- [`index.json`](https://github.com/nice-registry/all-the-package-repos/blob/master/index.json): the library baseline, and current library's main file
- [`data/packages.json`](https://github.com/nice-registry/all-the-package-repos/blob/master/data/packages.json): output from this new process, not yet published to npm.

The decision to duplicate the files will prevent breaking any consumer while we set and validate this new process.

The new one is currently being updated, and very soon will catch up, so once we confirm that those looks the same we will swap them and publish to npm. 

From there the process will be put on autopilot.

**Comment by zeke** [comment]
Thanks for the update, and please let me know if anything is need on my part.

**Pull request merged**
