### PR TITLE
Refresh README on update

### PR DESCRIPTION
**Pull request by LucasScotta**
This was proposed at https://github.com/nice-registry/all-the-package-repos/issues/27

@zeke Reopening https://github.com/nice-registry/all-the-package-repos/pull/33

### CODE REVIEW

**Review by zeke — COMMENTED** [review]
This is looking good! Is it ready to go?

What do you think about adding a new Actions workflow that runs `npm test` on pull requests?

**Comment by LucasScotta** [comment]
It's working.

@zeke sounds good. I have more test to open a new PR too

**Comment by eridal** [comment]
Nice! What's missing? let's merge this one

**Comment by zeke** [comment]
🤘🏼

**Pull request merged**
