### PR TITLE
[draft] Incremental updates

### PR DESCRIPTION
**Pull request by eridal**
I'm adding the draft for the **incremental updates** proposal.

Although it is still not complete, the code wont change much. What is currently missing is the fact that the end result is duplicated, so we are able to compare both datasets: `index.json` for the current process and `data/packages.json` which this script outputs. 

Also I've added [bitbucket-url-to-object](https://www.npmjs.com/package/bitbucket-url-to-object) but I'm still not sure if it is a good idea to be included as part of this change as doing so will amplify the divergence between the `index.json` and `data/packages.json`.

Before merging this we should unify those two datasets into a single one.

---

On a separate subject, the metadata (file `data/metadata.json`) is where the process keeps track of the previous executions, which this PR only include empty defaults, aka all zeros. I'm currently executing this process from my computer, which is a really expensive operation from my country's internet (and also why we needed the optional cache mechanism)

At this point it is not clear what is the best course of action, if either setup the process to execute from scratch, or manually configure the output of my manual executions. What we do know is that the process gets interrupted by really large documents (files of 60Mb+), which could prevent running safely this from the cloud: the end result of an interrupted execution will be to publish a new version with partial historical data.

This could be quickly validated by anyone with access to a faster internet: just execute the process from scratch and let's see if it is able to process the entire history in one go. Please remember doing so will take at least 3 hours.

---

Just for reference here are the metadata of my manual testing:

```js
{ packages: 754278,
  last: 5008165,
  latest: 5517514,
  runs: {
    total: 9
    status: { cancelled: 7, restart: 1, ok: 1 } },
  repos:
   { github: 743367,
     gitlab: 2433,
     bitbucket: 942,
     others: 7536 },
  stats:
   { changes: 824373,
     inserts: 754278,
     updates: 0,
     deletes: 36043,
     invalid: 34052,
     ignored: 0 },
  batch:
   { limit: 509351,
     since: 5008163,
     index: 5008165,
     until: 5517514,
     started: '2020-03-13T02:39:51.134Z',
     finished: '2020-03-13T02:41:38.945Z',
     took_ms: 107811,
     found: 2,
     status: 'cancelled' } }
```
cc @zeke's

### CODE REVIEW

**Comment by eridal** [comment]
> 
> standard: Use JavaScript Standard Style (http://standardjs.com)
> standard: Run `standard --fix` to automatically fix some problems.

Hello standard, we meet again.

It is a bit sad seeing how many well-written pieces needs to be broken in order to make this self-called standard happy.

That being said, I will submit the `--fix` next

**Comment by zeke** [comment]
Hey would you be willing to re-open this PR on a branch of the canonical repo, instead of from a fork? That would make it easier for me to pull these changes down and collaborate on this PR.

**Comment by eridal** [comment]
@zeke I dont have access to this repo.

```
ERROR: Permission to nice-registry/all-the-package-repos.git denied to eridal.
Please make sure you have the correct access rights and the repository exists.
```

**Comment by zeke** [comment]
Oops I didn't realize that. I've just made you an owner of the org. You should now have admin access to all the repos in @nice-registry.

**Comment by eridal** [comment]
> Oops I didn't realize that. I've just made you an owner of the org. You should now have admin access to all the repos in @nice-registry.

Odd, it is still not allowing me to push to this repo.

@zeke could you please check that this repo has access for nice-registry's members?

**Comment by zeke** [comment]
Sorry, the change didn't take effect before. I must have missed a 2FA prompt or something. Please try again:

Screen Shot 2020-03-16 at 9 06 35 AM

**Comment by eridal** [comment]
@zeke thank you!

I have the correct access now. I will focus on this during the next 2hs.

**Pull request closed without merging**
