### PR TITLE
Refactor the package

### LINKED ISSUE #27: Update build process to refresh stats in README
There used to be a part of the build process that updates the stats in the README:

```
<!-- stats -->
Packages | Count | Percentage
-------- | ----- | ----------
With repository in package.json | 824259 | 100%
On GitHub | 809594 |  98.22%
On BitBucket | 658 |  0.08%
On GitLab | 1014 |  0.12%
<!-- /stats -->
```

But it looks that has been disabled or removed, and now that table is out of date. Let's add it back.

cc @eridal who might have some context. No pressure to work on this!

### PR DESCRIPTION
**Pull request by zarianec**
Changes:
1. removed code for caching as it was not used anywhere
2. removed statistics per registry as it was not used anywhere and was pretty limited
3. changed handling of inactive/stack changes
4. fixed statistics in readme
5. updated dependencies

resolve #27 #30

### CODE REVIEW

**Comment by eridal** [comment]
Hey @zarianec

I appreciate the PR but I have a few concerns:

Firstly, the change is too wide. Maybe open a few PRs? Smaller in size and lot more focused, that way we could also focus the discussion and move forward easily. My goal here is to help you get your ideas into running code.

Secondly, the metadata change is destructive, meaning you are losing history!! It's better leave that to the script itself.. just change the code and it will change the metadata during the next execution. This will also get rid of the versioning conflict. 

The same applies to the npm package. Typically that is up to the repo maintainers to change. 

Thirdly that unused code is not er.. unused. That code was meant to be used when doing a full-history reprocess, so that devs can re-run the same process without the extra cost of getting millions of changes in each run. This is super useful if for some reason we decide to include a change that will make the current metadata outdated as the update script is only incremental.

Finally, I don't this we reached an agreement about the null-in-repo just yet, so thanks for adding into the convo! let's the ideas keep coming!!

**Comment by zarianec** [comment]
>Secondly, the metadata change is destructive

**Comment by zarianec** [comment]
>Secondly, the metadata change is destructive

I agree, it's not necessary to add metadata to the PR. I added it to demonstrate what changes will apply to it after the merge.

>The same applies to the npm package. Typically that is up to the repo maintainers to change.

It has to be rebuilt anyway if we decide to add null values to it. Having it in PR with recent changes together with a metadata file will allow updating it in minutes instead of hours of maintainer's time

>Thirdly that unused code is not er.. unused. That code was meant to be used when doing a full-history reprocess

This is based on assumption that the developer knows about that feature and found the environment variables in the code. This feature wasn't mentioned in the readme in any way. For a production run, it doesn't make sense as well so it rather looks like a dead code than a time saver.

Probably I should have added the section to the readme and describe how it can be used by developers so they don't need to find it in the code.

>Finally, I don't this we reached an agreement about the null-in-repo 

Based on the discussion in the issue and no reaction after the last comment there (https://github.com/nice-registry/all-the-package-repos/issues/30#issuecomment-910732024) I assumed that we are going to release a new major version with a breaking change.

We could probably think about what to do with a previous v1 and if it will get updates after the v2 release or not, but it's out of the scope of this PR I suppose.

**Review by zeke — CHANGES_REQUESTED** [review]
Hey @zarianec thanks for the PR! 🍰 

>  I assumed that we are going to release a new major version with a breaking change.

I'm in agreement with @zarianec this. 👍🏼 

---

> the change is too wide. Maybe open a few PRs? Smaller in size and lot more focused, that way we could also focus the discussion and move forward easily. My goal here is to help you get your ideas into running code.

☝🏼 I'm in agreement with @eridal on this. There are a lot of unrelated changes in this PR: version number bump, dependency updates, readme rewrite, renamed scripts, etc. I would be in favor of a smaller diff here that focuses specifically on getting package names with `null` repos into the mix. We can hash out the other changes here in separate issues/PRs.

**Comment by zarianec** [comment]
I'll open separate smaller PRs as was suggested by @eridal and @zeke

**Pull request closed without merging**
