### PR TITLE
Reduce diff size

### PR DESCRIPTION
**Pull request by eridal**
This will make the build script to alphabetical list the packages
on the `index.json`, which will reduce the diff size of the daily update.

This approach provides a nice side-effect that every day the diff
will only contain those packages that were added or removed since
the last update.

### CODE REVIEW

**Comment by zeke** [comment]
Hey thanks for the pull request. I like this idea. Did you happen to run this locally to get a sense of whether it is working as expected?

**Comment by eridal** [comment]
@zeke  Thanks for the quick answer!

Yeah, I tested this using the [debug's if](https://github.com/nice-registry/all-the-package-repos/blob/master/scripts/build.js#L37) with a dataset of 10k repos.

My only concern is that in order to sort the repos I needed to create a copy of all the keys, which might not be an issue if the machine has enough memory.

**Comment by zeke** [comment]
> I needed to create a copy of all the keys, which might not be an issue if the machine has enough memory.

That was exactly my concern. RAM is the biggest threat to this project's success. :)

I'm open to shipping it, letting it run its course, and checking in after a few days to see how the schedule jobs are panning out...

**Comment by eridal** [comment]
> That was exactly my concern. RAM is the biggest threat to this project's success. :)

Yeah, I was totally aware when designed this approach.

> I'm open to shipping it, letting it run its course, and checking in after a few days to see how the schedule jobs are panning out...

How long does the update takes? Maybe you can run pointed to the branch only for today

**Comment by zeke** [comment]
It runs once a day in a Heroku scheduled task. I don't get alerted when it fails, so one of us will have to remember to check and see if new versions are being published!

This project was created before GitHub Actions existed, but Actions would be an ideal platform on which to run this scheduled build and [release script](https://github.com/nice-registry/all-the-package-repos/blob/master/scripts/release.sh). If you have an interested in migrating this project to Actions, that would be really helpful, not just for me but for anyone who has an interest in the long term welfare (and reproduciblity) of this project. No pressure! Just a suggestion.

**Comment by zeke** [comment]
PS I watch a lot of repos and orgs. Please @zeke me in future issues or PRs so it doesn't fall through the cracks. Thanks!

**Comment by eridal** [comment]
> It runs once a day in a Heroku scheduled task. I don't get alerted when it fails, so one of us will have to remember to check and see if new versions are being published!

Cool, let's continue the conversation in a few days!

I been trying to play with Github Actions in the past. I'll try to find some time to use this opportunity and experiment with it :)

**Pull request merged**
